package ch.epfl.sweng.project.debug.local.database;

import java.util.Set;

/**
 * @author Amaury Combes
 *
 * The Node interface represents a link to an element of the local database used for tests
 * This interface is implemented by multiple class and some operations might not be supported
 * in all of them. This is because the data structure has some specific architecture (i.e. a three
 * of height 3)
 */
public interface Node {

    /**
     * Getter for the id of the current node
     *
     * @return the id of the current node
     */
    public String getId();

    /**
     * Getter for the children of the current node
     *
     * @return the children of the current node
     */
    public Set<Node> getChildren();

    /**
     * Tries to get a specific child of the current node
     *
     * @param id the id of child to get
     * @return the node with the corresponding id
     * @throws IllegalArgumentException if the id passed as argument does not exists
     */
    public Node getChild(String id) throws IllegalArgumentException;

    /**
     * Adds a child with a random id
     *
     * @return the node added
     */
    public Node addAutoGeneratedChild();

    /**
     * Add a child to the current node
     *
     * @param id the id of the child to add
     * @return the child that was just added
     */
    public Node addChild(String id);
}

