package ch.epfl.sweng.jassatepfl.database.local;


import java.util.Set;

/**
 * @author Amaury Combes
 *
 * The leaf class is a particular case of the Node interface. It represents the bottom of our
 * database.
 * Some operations are not supported
 */
public class Leaf implements Node {
    private String id;
    private Object data;

    /**
     * Constructor of the Leaf class
     *
     * @param id the id of the Leaf that is created
     */
    public Leaf(String id) {
        this.id = id;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public Set<Node> getChildren() {
        throw new UnsupportedOperationException("Leaf does not support getChildren()");
    }

    @Override
    public Node getChild(String id) {
        throw new UnsupportedOperationException("Leaf does not support getChild(id)");
    }

    @Override
    public Node addChild(String id) {
        throw new UnsupportedOperationException("Leaf does not support addChild(id)");
    }

    @Override
    public Node addAutoGeneratedChild() {
        throw new UnsupportedOperationException("Leaf does not support addAutoGeneratedChild()");
    }

    /**
     * Getter for the data of the current leaf
     *
     * @return the data of the current leaf
     */
    public Object getData() {
        return data;
    }

    /**
     * Setter for the data of the current leaf
     *
     * @param data the data that we need to add
     */
    public void setData(Object data) {
        this.data = data;
    }

    @Override
    public void dropChildren() {
        throw new UnsupportedOperationException();

    }
}
