package ch.epfl.sweng.jassatepfl.database.local;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * The TreeNode class is a special case of the Node interface. It represents the middle nodes of our
 * tree structure
 *
 * @author Amaury Combes
 */
public class TreeNode implements Node {

    private String id;
    private Set<Node> children;

    /**
     * Constructor of the TreeNode class
     *
     * @param id the id of the TreeNode that is created
     */
    public TreeNode(String id) {
        this.id = id;
        children = new HashSet<>();
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public Set<Node> getChildren() {
        return new HashSet<>(children);
    }

    @Override
    public Leaf getChild(String id) {
        for (Node n : children) {
            if (n.getId().equals(id)) {
                return (Leaf) n;
            }
        }
        throw new IllegalArgumentException("The node does not have a children named : " + id);
    }

    @Override
    public Leaf addChild(String id) {
        switch (this.id) {
            case "players":
                PlayerLeaf playerLeaf = new PlayerLeaf(id);
                children.add(playerLeaf);
                return playerLeaf;
            case "matches":
                MatchLeaf matchLeaf = new MatchLeaf(id);
                children.add(matchLeaf);
                return matchLeaf;
            case "pendingMatches":
                MatchStatusLeaf statusLeaf = new MatchStatusLeaf(id);
                children.add(statusLeaf);
                return statusLeaf;
            case "matchStats":
                MatchStatsLeaf statsLeaf = new MatchStatsLeaf(id);
                children.add(statsLeaf);
                return statsLeaf;
            default:
                throw new UnsupportedOperationException();
        }
    }

    @Override
    public Leaf addAutoGeneratedChild() {
        String tempId = randomStringGenerator();
        boolean safeCopy = false;

        while (!safeCopy) {
            safeCopy = true;
            for (Node n : children) {
                if (n.getId().equals(tempId)) {
                    safeCopy = false;
                    tempId = randomStringGenerator();
                }
            }
        }

        Leaf newLeaf;
        switch (this.id) {
            case "players":
                newLeaf = new PlayerLeaf(tempId);
                break;
            case "matches":
                newLeaf = new MatchLeaf(tempId);
                break;
            case "pendingMatches":
                newLeaf = new MatchStatusLeaf(tempId);
                break;
            case "stats":
                newLeaf = new MatchStatsLeaf(tempId);
                break;
            default:
                throw new UnsupportedOperationException("Cannot add an auto generated child to : " + id);
        }
        children.add(newLeaf);
        return newLeaf;
    }

    @Override
    public void dropChildren() {
        children = new HashSet<>();
    }

    private String randomStringGenerator() {
        return UUID.randomUUID().toString();
    }

    @Override
    public void initialize() {

    }

}
