package ch.epfl.sweng.project.database.tools;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * @author Amaury Combes
 *
 */
public interface Node {

    public String getId();

    public Set<Node> getChildren();

    public Node getChild(String id);

    public void addAutoGeneratedChild();
}

