package ch.epfl.sweng.project.database.tools;

import java.util.HashSet;
import java.util.Set;

/**
 * @author Amaury Combes
 */
public class Root implements Node {
    private final String id;
    private Set<Node> children;

    public Root(String id) {
        this.id = id;
        children = new HashSet<>();
    }

    public String getId() {
        return id;
    }

    public Set<Node> getChildren() {
        return new HashSet<>(children);
    }

    public Node getChild(String id) {
        for(Node n: children) {
            if(n.getId() == id) {
                return n;
            }
        }
        return null;
    }

    public void setData(Object data) {
        throw new UnsupportedOperationException("Root does not support setData()");
    }

    public void addAutoGeneratedChild() {
        throw new UnsupportedOperationException("Root does not support addAutoGeneratedChild()");
    }
}
