package ch.epfl.sweng.project.database.tools;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * @author Amaury Combes
 */
public class TreeNode implements Node {
    private String id;
    private Set<Node> children;

    public TreeNode(String id) {
        this.id = id;
        children = new HashSet<>();
    }

    public String getId() {
        return id;
    }

    public Set<Node> getChildren() {
        return new HashSet<>(children);
    }

    public Node getChild(String id) {
        for(Node n: children) {
            if(n.getId() == id) {
                return n;
            }
        }
        throw new IllegalArgumentException("The node does not have a children named : " + id);
    }

    public void setData(Object data) {
        throw new UnsupportedOperationException("Root does not support setData()");
    }

    public void addAutoGeneratedChild() {
        String tempId  = randomStringGenerator();
        boolean safeCopy = false;
        while(!safeCopy) {
            safeCopy = true;
            for(Node n: children) {
                if(n.getId() == tempId) {
                    safeCopy = false;
                    tempId = randomStringGenerator();
                } //end if
            } //end for
        } //end while
        children.add(new Leaf(tempId));
    }

    private String randomStringGenerator() {
        return UUID.randomUUID().toString();
    }
}
