package ch.epfl.sweng.jassatepfl.test_utils.database.local;


import java.util.Set;

/**
 * @author Amaury Combes
 */
public class LeafFieldTest<T> implements NodeTest {
    private final String id;
    private T data;

    public LeafFieldTest(String id) {
        this.id = id;
    }

    public LeafFieldTest(String id, T data) {
        this.id = id;
        this.data = data;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public Set<NodeTest> getChildren() {
        throw new UnsupportedOperationException("LeafFieldTest does not support getChildren()");
    }

    @Override
    public NodeTest getChild(String id) throws IllegalArgumentException {
        throw new UnsupportedOperationException("LeafFieldTest does not support getChild()");
    }

    @Override
    public NodeTest addAutoGeneratedChild() {
        throw new UnsupportedOperationException("LeafFieldTest does not support addAutoGeneratedChild()");
    }

    @Override
    public NodeTest addChild(String id) {
        throw new UnsupportedOperationException("LeafFieldTest does not support addChild()");
    }

    @Override
    public void dropChildren() {
        throw new UnsupportedOperationException("LeafFieldTest does not support dropChildren()");
    }

    @Override
    public void initialize() {
        throw new UnsupportedOperationException("LeafFieldTest does not support initialize()");
    }
}
