package ch.epfl.sweng.jassatepfl.test_utils.database.local;


import java.util.Set;

/**
 * @author Amaury Combes
 */
public class LeafField<T> implements Node {
    private final String id;
    private T data;

    public LeafField(String id) {
        this.id = id;
    }

    public LeafField(String id, T data) {
        this.id = id;
        this.data = data;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public Set<Node> getChildren() {
        throw new UnsupportedOperationException("LeafField does not support getChildren()");
    }

    @Override
    public Node getChild(String id) throws IllegalArgumentException {
        throw new UnsupportedOperationException("LeafField does not support getChild()");
    }

    @Override
    public Node addAutoGeneratedChild() {
        throw new UnsupportedOperationException("LeafField does not support addAutoGeneratedChild()");
    }

    @Override
    public Node addChild(String id) {
        throw new UnsupportedOperationException("LeafField does not support addChild()");
    }

    @Override
    public void dropChildren() {
        throw new UnsupportedOperationException("LeafField does not support dropChildren()");
    }

    @Override
    public void initialize() {
        throw new UnsupportedOperationException("LeafField does not support initialize()");
    }
}
