package ch.epfl.sweng.jassatepfl.test_utils.database.local;


import java.util.Set;

public abstract class NodeTest extends CustomObservable {
    protected boolean isDeleted;
    /**
     * Getter for the id of the current node
     *
     * @return the id of the current node
     */
    abstract public String getId();

    /**
     * Getter for the children of the current node
     *
     * @return the children of the current node
     */
    abstract public Set<NodeTest> getChildren();

    abstract public NodeTest getParent();

    /**
     * Tries to get a specific child of the current node
     *
     * @param id the id of child to get
     * @return the node with the corresponding id
     * @throws IllegalArgumentException if the id passed as argument does not exists
     */
    abstract public NodeTest getChild(String id) throws IllegalArgumentException;

    /**
     * Adds a child with a random id
     *
     * @return the node added
     */
    abstract public NodeTest addAutoGeneratedChild();

    /**
     * Add a child to the current node
     *
     * @param id the id of the child to add
     * @return the child that was just added
     */
    abstract public NodeTest addChild(String id);

    /**
     * Remove the current node from the database
     */
    abstract public void removeSelf();

    abstract public void removeChild(NodeTest child);

    /**
     * Remove all chidren of the current node
     */
    abstract public void dropChildren();

    abstract public void initialize();

    public boolean isDeleted() {
        return isDeleted;
    }
}
